### ISSUE TITLE
window offscreen

### ISSUE THREAD

**Issue by kyle-sylvestre** [matiasjpedro/CrazyTown#18]
The window is offscreen for me without any way to move it with my mouse. I was able to show it by hovering over the taskbar icon, right clicking the preview window, then selecting maximize. I use 1920x1080 resolution at 175% scaling.

**Comment by matiasjpedro** [comment]
I think this was because I was forcing the position of the windows, this will be fixed in the next build, now the default position will be 0,0 and you can specify an starting position using the new command args -win_pos_x number -win_pos_y number.

Thanks for the report 🙏
